apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: genesis-ai-requirements-api
  annotations:
    github.com/project-slug: emisgroup/genesis-ai-requirements-api
spec:
  type: service
  lifecycle: production
  owner: group:default/architecture
