<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Genesis.AI.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Genesis.AI.Core\Genesis.AI.Core.csproj" />
  </ItemGroup>

</Project>
