#!/usr/bin/env bash
# ==============================================================================
# generate-seed.sh — Extracts data from the running local DB and generates
# a new db/seed-local.sql file.
#
# Usage:
#   ./db/generate-seed.sh <project_id> [--description "override text"]
#
# Prerequisites:
#   - docker compose up -d (postgres must be running)
#
# Example:
#   ./db/generate-seed.sh 03735ad1-8759-414e-a93f-ce8cc7bfc1fc \
#     --description "A chatbot for the partner portal..."
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE="${SCRIPT_DIR}/seed-local.sql"
DB_NAME="genesis_ai_requirements"
DB_USER="postgres"
CONTAINER_SERVICE="postgres"

# --- Argument parsing ---
PROJECT_ID=""
DESCRIPTION_OVERRIDE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --description)
      DESCRIPTION_OVERRIDE="$2"
      shift 2
      ;;
    -*)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
    *)
      PROJECT_ID="$1"
      shift
      ;;
  esac
done

if [[ -z "$PROJECT_ID" ]]; then
  echo "Usage: $0 <project_id> [--description \"override text\"]" >&2
  echo "" >&2
  echo "Available projects:" >&2
  docker compose exec -T "$CONTAINER_SERVICE" psql -U "$DB_USER" -d "$DB_NAME" \
    --no-align -t -c "SELECT project_id || ' | ' || code || ' | ' || name FROM project WHERE is_deleted = false ORDER BY created_at;" >&2
  exit 1
fi

# --- Helper: run SQL and return raw output ---
run_sql() {
  docker compose exec -T "$CONTAINER_SERVICE" psql -U "$DB_USER" -d "$DB_NAME" --no-align -t -c "$1"
}

# --- Verify project exists ---
PROJECT_EXISTS=$(run_sql "SELECT 1 FROM project WHERE project_id = '${PROJECT_ID}' AND is_deleted = false;")
if [[ "$PROJECT_EXISTS" != "1" ]]; then
  echo "Error: Project ${PROJECT_ID} not found or is deleted." >&2
  exit 1
fi

echo "Extracting data for project ${PROJECT_ID}..."

# --- Count data for progress ---
MSG_COUNT=$(run_sql "SELECT COUNT(*) FROM message WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}'));")
PARKING_COUNT=$(run_sql "SELECT COUNT(*) FROM parking_lot_item WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}'));")
USAGE_COUNT=$(run_sql "SELECT COUNT(*) FROM token_usage WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}'));")
ARTEFACT_COUNT=$(run_sql "SELECT COUNT(*) FROM artefact WHERE project_id = '${PROJECT_ID}';")

echo "  Found: ${MSG_COUNT} messages, ${PARKING_COUNT} parking lot items, ${USAGE_COUNT} token usage records, ${ARTEFACT_COUNT} artefacts"
echo "  Generating SQL (this may take a moment for large conversations)..."

# --- Handle description override ---
DESC_OVERRIDE_SQL="NULL"
if [[ -n "$DESCRIPTION_OVERRIDE" ]]; then
  ESCAPED_DESC=$(echo "$DESCRIPTION_OVERRIDE" | sed "s/'/''/g")
  DESC_OVERRIDE_SQL="'${ESCAPED_DESC}'"
fi

# --- Generate the seed file using pure SQL with format() for proper escaping ---
# All quoting is handled by PostgreSQL's format(%L, ...) which correctly
# escapes single quotes, newlines, and special characters in content.
docker compose exec -T "$CONTAINER_SERVICE" psql -U "$DB_USER" -d "$DB_NAME" \
  -t --no-align -P pager=off << EOSQL > "$OUTPUT_FILE"

SELECT '-- Local seed data — generated by db/generate-seed.sh on ' || now()::date::text;
SELECT '-- Run with: docker compose up -d (seed service)';
SELECT '-- This is NOT a Flyway migration — it is a manual local-only script.';
SELECT '-- The seed entrypoint (docker-compose.yml) skips if the project code already exists.';
SELECT '';

SELECT '-- Clean up any existing seed data for this project';
SELECT format('DELETE FROM token_usage WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = %L));', '${PROJECT_ID}');
SELECT format('DELETE FROM parking_lot_item WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = %L));', '${PROJECT_ID}');
SELECT format('DELETE FROM message WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = %L));', '${PROJECT_ID}');
SELECT format('DELETE FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = %L);', '${PROJECT_ID}');
SELECT format('DELETE FROM artefact WHERE project_id = %L;', '${PROJECT_ID}');
SELECT format('DELETE FROM pipeline_stage WHERE project_id = %L;', '${PROJECT_ID}');
SELECT format('DELETE FROM project WHERE project_id = %L;', '${PROJECT_ID}');
SELECT '';

SELECT '-- ============================================================';
SELECT '-- PROJECT: ' || name FROM project WHERE project_id = '${PROJECT_ID}';
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO project (project_id, code, name, description, compliance_domain, status, created_by, created_at, updated_at, is_deleted) VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, false);',
  project_id, code, name,
  COALESCE(${DESC_OVERRIDE_SQL}, description),
  compliance_domain::text, status::text, created_by, created_at, updated_at
) FROM project WHERE project_id = '${PROJECT_ID}';
SELECT '';

SELECT '-- Pipeline stages';
SELECT format(
  'INSERT INTO pipeline_stage (pipeline_stage_id, project_id, stage_type, status, sort_order, iteration, started_at, completed_at, completed_by) VALUES (%L, %L, %L, %L, %s, %s, %s, %s, %s);',
  pipeline_stage_id, project_id, stage_type::text, status::text, sort_order, iteration,
  COALESCE(format('%L', started_at), 'NULL'),
  COALESCE(format('%L', completed_at), 'NULL'),
  COALESCE(format('%L', completed_by), 'NULL')
) FROM pipeline_stage WHERE project_id = '${PROJECT_ID}' ORDER BY sort_order;
SELECT '';

SELECT '-- ============================================================';
SELECT '-- CONVERSATIONS';
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO conversation (conversation_id, stage_id, status, message_count, current_phase, phase_name, total_phases, questions_asked, estimated_total_questions, requirements_captured, created_at, resumed_at) VALUES (%L, %L, %L, %s, %s, %L, %s, %s, %s, %s, %L, %s);',
  conversation_id, stage_id, status::text, message_count, current_phase, phase_name, total_phases, questions_asked,
  COALESCE(estimated_total_questions::text, 'NULL'),
  requirements_captured, created_at,
  COALESCE(format('%L', resumed_at), 'NULL')
) FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}') ORDER BY created_at;
SELECT '';

SELECT '-- ============================================================';
SELECT format('-- MESSAGES (%s total)', COUNT(*)) FROM message WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}'));
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO message (message_id, conversation_id, role, content, token_count, user_ern, given_name, family_name, created_at) VALUES (%L, %L, %L, %L, %s, %s, %s, %s, %L);',
  message_id, conversation_id, role::text, content,
  COALESCE(token_count::text, 'NULL'),
  COALESCE(format('%L', user_ern), 'NULL'),
  COALESCE(format('%L', given_name), 'NULL'),
  COALESCE(format('%L', family_name), 'NULL'),
  created_at
) FROM message WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}')) ORDER BY created_at;
SELECT '';

SELECT '-- ============================================================';
SELECT '-- PARKING LOT ITEMS';
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO parking_lot_item (parking_lot_item_id, conversation_id, content, priority, status, source_phase, resolved_at, created_at) VALUES (%L, %L, %L, %L, %L, %s, %s, %L);',
  parking_lot_item_id, conversation_id, content, priority::text, status::text, source_phase,
  COALESCE(format('%L', resolved_at), 'NULL'),
  created_at
) FROM parking_lot_item WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}')) ORDER BY created_at;
SELECT '';

SELECT '-- ============================================================';
SELECT '-- TOKEN USAGE';
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO token_usage (token_usage_id, conversation_id, input_tokens, output_tokens, cache_read_input_tokens, cache_write_input_tokens, created_at) VALUES (%L, %L, %s, %s, %s, %s, %L);',
  token_usage_id, conversation_id, input_tokens, output_tokens, cache_read_input_tokens, cache_write_input_tokens, created_at
) FROM token_usage WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}')) ORDER BY created_at;
SELECT '';

SELECT '-- ============================================================';
SELECT '-- ARTEFACTS';
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO artefact (artefact_id, project_id, version, file_path, content_type, content, size_bytes, created_by, created_at) VALUES (%L, %L, %s, %L, %L, %L, %s, %L, %L);',
  artefact_id, project_id, version, file_path, content_type, content,
  COALESCE(size_bytes::text, 'NULL'),
  created_by, created_at
) FROM artefact WHERE project_id = '${PROJECT_ID}' ORDER BY file_path, version;

EOSQL

# Remove empty lines that psql outputs for NULL results
sed -i '' '/^$/d' "$OUTPUT_FILE"

# Count what was generated
LINE_COUNT=$(wc -l < "$OUTPUT_FILE" | tr -d ' ')
BYTE_COUNT=$(wc -c < "$OUTPUT_FILE" | tr -d ' ')
MSG_INSERTS=$(grep -c "INSERT INTO message" "$OUTPUT_FILE" || true)

echo ""
echo "Done! Generated: ${OUTPUT_FILE}"
echo "  Size: ${BYTE_COUNT} bytes, ${LINE_COUNT} lines"
echo "  Messages: ${MSG_INSERTS} INSERT statements"
echo ""
echo "To apply fresh: docker compose down -v && docker compose up -d"
echo ""

# Check if project code differs from docker-compose expectation
P_CODE=$(run_sql "SELECT code FROM project WHERE project_id = '${PROJECT_ID}';")
if [[ "$P_CODE" != "QAB-001" ]]; then
  echo "WARNING: Project code is '${P_CODE}' — update docker-compose.yml seed entrypoint"
  echo "  (currently checks for 'QAB-001')"
fi
