#!/usr/bin/env bash
# ==============================================================================
# generate-seed.sh — Extracts data from the running local DB and generates a
# per-project seed file at db/seeds/<project_code>.sql. Also extracts artefact
# content from S3 (LocalStack) into db/seed-artefacts/ so it is re-uploaded on a
# fresh boot. The seed service runs every db/seeds/*.sql file that exists, so
# multiple projects can be seeded side by side.
#
# Usage:
#   ./db/generate-seed.sh <project_id> [--description "override text"]
#
# Prerequisites:
#   - docker compose up -d (postgres and localstack must be running)
#
# Example:
#   ./db/generate-seed.sh 03735ad1-8759-414e-a93f-ce8cc7bfc1fc \
#     --description "A chatbot for the partner portal..."
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SEEDS_DIR="${SCRIPT_DIR}/seeds"
SEED_ARTEFACTS_DIR="${SCRIPT_DIR}/seed-artefacts"
DB_NAME="genesis_ai_requirements"
DB_USER="postgres"
CONTAINER_SERVICE="postgres"
LOCALSTACK_SERVICE="localstack"
S3_BUCKET="genesis-ai-artefacts"

# --- Argument parsing ---
PROJECT_ID=""
DESCRIPTION_OVERRIDE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --description)
      DESCRIPTION_OVERRIDE="$2"
      shift 2
      ;;
    -*)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
    *)
      PROJECT_ID="$1"
      shift
      ;;
  esac
done

if [[ -z "$PROJECT_ID" ]]; then
  echo "Usage: $0 <project_id> [--description \"override text\"]" >&2
  echo "" >&2
  echo "Available projects:" >&2
  docker compose exec -T "$CONTAINER_SERVICE" psql -U "$DB_USER" -d "$DB_NAME" \
    --no-align -t -c "SELECT project_id || ' | ' || code || ' | ' || name FROM project WHERE is_deleted = false ORDER BY created_at;" >&2
  exit 1
fi

# --- Helper: run SQL and return raw output ---
run_sql() {
  docker compose exec -T "$CONTAINER_SERVICE" psql -U "$DB_USER" -d "$DB_NAME" --no-align -t -c "$1"
}

# --- Verify project exists ---
PROJECT_EXISTS=$(run_sql "SELECT 1 FROM project WHERE project_id = '${PROJECT_ID}' AND is_deleted = false;")
if [[ "$PROJECT_EXISTS" != "1" ]]; then
  echo "Error: Project ${PROJECT_ID} not found or is deleted." >&2
  exit 1
fi

# --- Resolve the project code; each project gets its own seed file ---
PROJECT_CODE=$(run_sql "SELECT code FROM project WHERE project_id = '${PROJECT_ID}';" | tr -d '[:space:]')
if [[ -z "$PROJECT_CODE" ]]; then
  echo "Error: Could not resolve project code for ${PROJECT_ID}." >&2
  exit 1
fi
mkdir -p "$SEEDS_DIR"
OUTPUT_FILE="${SEEDS_DIR}/${PROJECT_CODE}.sql"

echo "Extracting data for project ${PROJECT_ID} (${PROJECT_CODE})..."

# --- Count data for progress ---
MSG_COUNT=$(run_sql "SELECT COUNT(*) FROM message WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}'));")
PARKING_COUNT=$(run_sql "SELECT COUNT(*) FROM parking_lot_item WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}'));")
USAGE_COUNT=$(run_sql "SELECT COUNT(*) FROM token_usage WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}'));")
ARTEFACT_COUNT=$(run_sql "SELECT COUNT(*) FROM artefact WHERE project_id = '${PROJECT_ID}';")
NOTE_COUNT=$(run_sql "SELECT COUNT(*) FROM project_note WHERE project_id = '${PROJECT_ID}';")
DECISION_COUNT=$(run_sql "SELECT COUNT(*) FROM project_decision WHERE project_id = '${PROJECT_ID}';")

echo "  Found: ${MSG_COUNT} messages, ${PARKING_COUNT} parking lot items, ${USAGE_COUNT} token usage records, ${ARTEFACT_COUNT} artefacts, ${NOTE_COUNT} notes, ${DECISION_COUNT} decisions"
echo "  Generating SQL (this may take a moment for large conversations)..."

# --- Handle description override ---
DESC_OVERRIDE_SQL="NULL"
if [[ -n "$DESCRIPTION_OVERRIDE" ]]; then
  ESCAPED_DESC=$(echo "$DESCRIPTION_OVERRIDE" | sed "s/'/''/g")
  DESC_OVERRIDE_SQL="'${ESCAPED_DESC}'"
fi

# --- Generate the seed file using pure SQL with format() for proper escaping ---
# All quoting is handled by PostgreSQL's format(%L, ...) which correctly
# escapes single quotes, newlines, and special characters in content.
docker compose exec -T "$CONTAINER_SERVICE" psql -U "$DB_USER" -d "$DB_NAME" \
  -t --no-align -P pager=off << EOSQL > "$OUTPUT_FILE"

SELECT '-- Local seed data — generated by db/generate-seed.sh on ' || now()::date::text;
SELECT '-- Run with: docker compose up -d (seed service)';
SELECT '-- This is NOT a Flyway migration — it is a manual local-only script.';
SELECT '-- The seed service runs every db/seeds/*.sql file; each file deletes and';
SELECT '-- re-inserts its own project, so re-running is idempotent.';
SELECT '';

SELECT '-- Clean up any existing seed data for this project';
SELECT format('DELETE FROM token_usage WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = %L));', '${PROJECT_ID}');
SELECT format('DELETE FROM parking_lot_item WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = %L));', '${PROJECT_ID}');
SELECT format('DELETE FROM message WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = %L));', '${PROJECT_ID}');
SELECT format('DELETE FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = %L);', '${PROJECT_ID}');
SELECT format('DELETE FROM artefact WHERE project_id = %L;', '${PROJECT_ID}');
SELECT format('DELETE FROM project_note WHERE project_id = %L;', '${PROJECT_ID}');
SELECT format('DELETE FROM project_decision WHERE project_id = %L;', '${PROJECT_ID}');
SELECT format('DELETE FROM pipeline_stage WHERE project_id = %L;', '${PROJECT_ID}');
SELECT format('DELETE FROM project WHERE project_id = %L;', '${PROJECT_ID}');
SELECT '';

SELECT '-- ============================================================';
SELECT '-- PROJECT: ' || name FROM project WHERE project_id = '${PROJECT_ID}';
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO project (project_id, code, name, description, time_sheet_code, compliance_domain, status, created_by, created_at, updated_at, is_deleted) VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, false);',
  project_id, code, name,
  COALESCE(${DESC_OVERRIDE_SQL}, description),
  time_sheet_code,
  compliance_domain::text, status::text, created_by, created_at, updated_at
) FROM project WHERE project_id = '${PROJECT_ID}';
SELECT '';

SELECT '-- Pipeline stages';
SELECT format(
  'INSERT INTO pipeline_stage (pipeline_stage_id, project_id, stage_type, status, sort_order, iteration, started_at, completed_at, completed_by) VALUES (%L, %L, %L, %L, %s, %s, %s, %s, %s);',
  pipeline_stage_id, project_id, stage_type::text, status::text, sort_order, iteration,
  COALESCE(format('%L', started_at), 'NULL'),
  COALESCE(format('%L', completed_at), 'NULL'),
  COALESCE(format('%L', completed_by), 'NULL')
) FROM pipeline_stage WHERE project_id = '${PROJECT_ID}' ORDER BY sort_order;
SELECT '';

SELECT '-- ============================================================';
SELECT '-- CONVERSATIONS';
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO conversation (conversation_id, stage_id, status, message_count, current_phase, phase_name, total_phases, questions_asked, estimated_total_questions, requirements_captured, created_at, resumed_at) VALUES (%L, %L, %L, %s, %s, %L, %s, %s, %s, %s, %L, %s);',
  conversation_id, stage_id, status::text, message_count, current_phase, phase_name, total_phases, questions_asked,
  COALESCE(estimated_total_questions::text, 'NULL'),
  requirements_captured, created_at,
  COALESCE(format('%L', resumed_at), 'NULL')
) FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}') ORDER BY created_at;
SELECT '';

SELECT '-- ============================================================';
SELECT format('-- MESSAGES (%s total)', COUNT(*)) FROM message WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}'));
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO message (message_id, conversation_id, role, content, token_count, user_ern, given_name, family_name, created_at) VALUES (%L, %L, %L, %L, %s, %s, %s, %s, %L);',
  message_id, conversation_id, role::text, content,
  COALESCE(token_count::text, 'NULL'),
  COALESCE(format('%L', user_ern), 'NULL'),
  COALESCE(format('%L', given_name), 'NULL'),
  COALESCE(format('%L', family_name), 'NULL'),
  created_at
) FROM message WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}')) ORDER BY created_at;
SELECT '';

SELECT '-- ============================================================';
SELECT '-- PARKING LOT ITEMS';
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO parking_lot_item (parking_lot_item_id, conversation_id, content, priority, status, source_phase, resolved_at, created_at) VALUES (%L, %L, %L, %L, %L, %s, %s, %L);',
  parking_lot_item_id, conversation_id, content, priority::text, status::text, source_phase,
  COALESCE(format('%L', resolved_at), 'NULL'),
  created_at
) FROM parking_lot_item WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}')) ORDER BY created_at;
SELECT '';

SELECT '-- ============================================================';
SELECT '-- TOKEN USAGE';
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO token_usage (token_usage_id, conversation_id, input_tokens, output_tokens, cache_read_input_tokens, cache_write_input_tokens, created_at) VALUES (%L, %L, %s, %s, %s, %s, %L);',
  token_usage_id, conversation_id, input_tokens, output_tokens, cache_read_input_tokens, cache_write_input_tokens, created_at
) FROM token_usage WHERE conversation_id IN (SELECT conversation_id FROM conversation WHERE stage_id IN (SELECT pipeline_stage_id FROM pipeline_stage WHERE project_id = '${PROJECT_ID}')) ORDER BY created_at;
SELECT '';

SELECT '-- ============================================================';
SELECT '-- ARTEFACTS';
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO artefact (artefact_id, project_id, version, file_path, s3_key, content_type, size_bytes, created_by, created_at) VALUES (%L, %L, %s, %L, %L, %L, %s, %L, %L);',
  artefact_id, project_id, version, file_path, s3_key, content_type,
  COALESCE(size_bytes::text, 'NULL'),
  created_by, created_at
) FROM artefact WHERE project_id = '${PROJECT_ID}' ORDER BY file_path, version;
SELECT '';

SELECT '-- ============================================================';
SELECT '-- PROJECT NOTES';
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO project_note (project_note_id, project_id, content, author_ern, author_given_name, author_family_name, created_at, updated_at) VALUES (%L, %L, %L, %s, %s, %s, %L, %L);',
  project_note_id, project_id, content,
  COALESCE(format('%L', author_ern), 'NULL'),
  COALESCE(format('%L', author_given_name), 'NULL'),
  COALESCE(format('%L', author_family_name), 'NULL'),
  created_at, updated_at
) FROM project_note WHERE project_id = '${PROJECT_ID}' ORDER BY created_at;
SELECT '';

SELECT '-- ============================================================';
SELECT '-- PROJECT DECISIONS';
SELECT '-- ============================================================';
SELECT '';
SELECT format(
  'INSERT INTO project_decision (project_decision_id, project_id, title, context, decision, consequences, author_ern, author_given_name, author_family_name, created_at, updated_at) VALUES (%L, %L, %L, %L, %L, %L, %s, %s, %s, %L, %L);',
  project_decision_id, project_id, title, context, decision, consequences,
  COALESCE(format('%L', author_ern), 'NULL'),
  COALESCE(format('%L', author_given_name), 'NULL'),
  COALESCE(format('%L', author_family_name), 'NULL'),
  created_at, updated_at
) FROM project_decision WHERE project_id = '${PROJECT_ID}' ORDER BY created_at;

EOSQL

# Remove empty lines that psql outputs for NULL results
sed -i '' '/^$/d' "$OUTPUT_FILE"

# Count what was generated
LINE_COUNT=$(wc -l < "$OUTPUT_FILE" | tr -d ' ')
BYTE_COUNT=$(wc -c < "$OUTPUT_FILE" | tr -d ' ')
MSG_INSERTS=$(grep -c "INSERT INTO message" "$OUTPUT_FILE" || true)

# --- Extract artefact content from S3 (LocalStack) into db/seed-artefacts/ ---
# The artefact table only stores the s3_key; the actual content lives in S3.
# init-s3.sh re-uploads everything under db/seed-artefacts/ on a fresh boot, so
# the extracted tree must mirror the S3 key layout exactly.
echo "  Extracting artefact content from S3 (LocalStack)..."

# Remove any previously-extracted content for this project to avoid stale files.
rm -rf "${SEED_ARTEFACTS_DIR:?}/projects/${PROJECT_ID}"

S3_PREFIX="projects/${PROJECT_ID}/"
ARTEFACT_KEYS=$(docker compose exec -T "$LOCALSTACK_SERVICE" \
  awslocal s3api list-objects-v2 --bucket "$S3_BUCKET" --prefix "$S3_PREFIX" \
  --query 'Contents[].Key' --output text 2>/dev/null | tr '\t' '\n' | grep -v '^None$' || true)

S3_OBJECT_COUNT=0
if [[ -n "$ARTEFACT_KEYS" ]]; then
  while IFS= read -r KEY; do
    [[ -z "$KEY" ]] && continue
    DEST="${SEED_ARTEFACTS_DIR}/${KEY}"
    mkdir -p "$(dirname "$DEST")"
    # Redirect stdin from /dev/null so 'docker compose exec' does not consume
    # the while-loop's stdin (which would swallow the remaining keys).
    docker compose exec -T "$LOCALSTACK_SERVICE" \
      awslocal s3 cp "s3://${S3_BUCKET}/${KEY}" - < /dev/null > "$DEST"
    S3_OBJECT_COUNT=$((S3_OBJECT_COUNT + 1))
  done <<< "$ARTEFACT_KEYS"
fi
echo "  Extracted ${S3_OBJECT_COUNT} artefact object(s) to seed-artefacts/"

if [[ "$S3_OBJECT_COUNT" != "$ARTEFACT_COUNT" ]]; then
  echo "  WARNING: ${ARTEFACT_COUNT} artefact row(s) in DB but ${S3_OBJECT_COUNT} object(s) in S3 — some content may be missing."
fi

echo ""
echo "Done! Generated: ${OUTPUT_FILE}"
echo "  Size: ${BYTE_COUNT} bytes, ${LINE_COUNT} lines"
echo "  Messages: ${MSG_INSERTS} INSERT statements"
echo "  Artefacts: ${S3_OBJECT_COUNT} object(s) extracted to seed-artefacts/projects/${PROJECT_ID}"
echo ""
echo "To apply fresh: docker compose down -v && docker compose up -d"
echo "  (the seed service runs every db/seeds/*.sql file that exists)"
echo ""
