using System.Reflection;
using System.Runtime.CompilerServices;
using Genesis.AI.Domain.Interfaces;

namespace Genesis.AI.Infrastructure.Services;

/// <summary>
/// Stub implementation of <see cref="IPrototypeDemoGenerationService"/>. Returns a
/// deterministic single-page prototype-demo HTML document with no Bedrock call.
/// Satisfies all four Day 0 harness checks:
/// <list type="bullet">
/// <item>"PROTOTYPE ONLY" banner present in output.</item>
/// <item><c>emis-x-base.css</c> content inlined into <c>&lt;head&gt;</c>.</item>
/// <item>Complete <c>&lt;!DOCTYPE html&gt;…&lt;/html&gt;</c> document.</item>
/// <item>No format-valid NHS numbers (<c>\d{3}\s?\d{3}\s?\d{4}</c>).</item>
/// </list>
/// Yields the HTML in a single chunk; the <see cref="IAsyncEnumerable{T}"/> contract
/// is preserved so the controller can switch to SSE streaming on Day 2 without
/// touching this class.
/// </summary>
public sealed class StubPrototypeDemoGenerationService : IPrototypeDemoGenerationService
{
    private const string EmisXBaseCssResourceName =
        "Genesis.AI.Infrastructure.Resources.emis-x-base.css";

    public async IAsyncEnumerable<string> GenerateAsync(
        string projectName,
        [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        await Task.CompletedTask;

        var css = LoadEmbeddedCss();

        yield return $$"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <title>Prototype Demo — {{projectName}}</title>
              <style>
            {{css}}
              </style>
            </head>
            <body>
              <div role="banner" style="
                background:var(--token-colour-feedback-background-warning,#fff4cc);
                border:2px solid var(--token-colour-feedback-border-warning,#ffc200);
                color:var(--token-colour-feedback-text-warning,#594200);
                padding:0.75rem 1rem;
                font-family:var(--font-family,sans-serif);
                font-weight:600;">
                ⚠ PROTOTYPE ONLY — not for clinical use. All data shown is entirely fictional.
              </div>
              <main style="padding:2rem;font-family:var(--font-family,sans-serif);">
                <h1>{{projectName}}</h1>
                <p>This is a placeholder prototype page generated by the stub service.</p>
                <p>Patient: <strong>Alex Sample</strong> — ID: <strong>DEMO-0000</strong></p>
              </main>
            </body>
            </html>
            """;
    }

    private static string LoadEmbeddedCss()
    {
        var assembly = Assembly.GetExecutingAssembly();
        using var stream = assembly.GetManifestResourceStream(EmisXBaseCssResourceName)
            ?? throw new InvalidOperationException(
                $"Embedded resource not found: {EmisXBaseCssResourceName}");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}
